# Generated by Django 4.0.6 on 2022-08-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_asian_description_alter_asian_ingrediants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asian',
            old_name='ingrediants',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='italian',
            old_name='ingrediants',
            new_name='ingredients',
        ),
    ]
